import type { FamilyProfile, ChildProfile } from '@/types';

// In production this would be a database. For demo we use in-memory store.
export const families: FamilyProfile[] = [
  {
    id: 'f1',
    createdAt: new Date().toISOString(),
    contactName: 'Mito Freecss',
    email: 'mito@example.com',
    phone: '+1-555-0101',
    location: 'Whale Island',
    householdSize: 2,
    otherChildren: 0,
    otherAdults: 0,
    housingType: 'house',
    hasYard: true,
    pets: [],
    preferredAgeRange: [10, 14],
    preferredSiblingGroup: false,
    openToSpecialNeeds: true,
    maxChildren: 1,
    languages: ['Japanese', 'English'],
    occupation: 'Farmer',
    incomeStability: 'stable',
    verificationStatus: 'approved',
    backgroundCheck: {
      id: 'bc1',
      adopterId: 'f1',
      status: 'passed',
      method: 'manual',
      checkedAt: new Date().toISOString(),
      redFlags: [],
    },
  },
  {
    id: 'f2',
    createdAt: new Date().toISOString(),
    contactName: 'Leorio Paradinight',
    email: 'leorio@example.com',
    phone: '+1-555-0102',
    location: 'Yorknew City',
    householdSize: 2,
    otherChildren: 0,
    otherAdults: 1,
    housingType: 'apartment',
    hasYard: false,
    pets: ['cat'],
    preferredAgeRange: [8, 16],
    preferredSiblingGroup: true,
    openToSpecialNeeds: true,
    maxChildren: 2,
    languages: ['Japanese'],
    occupation: 'Medical student',
    incomeStability: 'stable',
    verificationStatus: 'in_review',
    backgroundCheck: {
      id: 'bc2',
      adopterId: 'f2',
      status: 'pending',
      method: 'manual',
      redFlags: [],
    },
  },
];

export const children: ChildProfile[] = [
  {
    id: 'c1',
    createdAt: new Date().toISOString(),
    displayName: 'Kite',
    age: 12,
    needs: ['emotional support', 'stability'],
    preferences: ['outdoor activities', 'nature'],
    interests: ['fishing', 'exploring'],
    shortDescription: 'A kind and curious child who loves the outdoors.',
    requiresStableIncome: true,
    status: 'available',
  },
  {
    id: 'c2',
    createdAt: new Date().toISOString(),
    displayName: 'Alluka',
    age: 10,
    needs: ['medical', 'emotional support', 'sibling preference'],
    preferences: ['quiet home', 'patient caregivers'],
    interests: ['reading', 'art'],
    siblingGroupId: 'sib1',
    shortDescription: 'Creative and gentle. Does best in a calm environment.',
    requiresStableIncome: true,
    prefersNoPets: false,
    status: 'available',
  },
  {
    id: 'c3',
    createdAt: new Date().toISOString(),
    displayName: 'Zushi',
    age: 9,
    needs: ['stability', 'mentorship'],
    preferences: ['sports', 'discipline'],
    interests: ['martial arts', 'training'],
    shortDescription: 'Energetic and determined. Loves structure and goals.',
    requiresStableIncome: true,
    status: 'available',
  },
];
